### ISSUE TITLE
Make 'scaleBilinear' polymorphic with respect to pixel type

### ISSUE THREAD

**Issue by mrkkrp** [mrkkrp/JuicyPixels-extra#2]
We actually should be able to do this without performance regressions.

**Comment by mrkkrp** [comment]
After several hours of experimenting (!) it looks impossible. Somehow GHC does not specialize properly in this case.

**Comment by naushadh** [comment]
Any updates on this issue? I'd like to be able to resize _any_ (or at-least most of) `DynamicImage`.

`JuicyPixels-extra` currently supports `PixelRGB8` only, but I stumbled upon a `PixelRGB16` scaling in [afcondon/juicy-pixel-processor](https://github.com/afcondon/juicy-pixel-processor): [Scaler16.hs](https://github.com/afcondon/juicy-pixel-processor/blob/master/app/Scaler16.hs).

Based on the `JuicyPixels` [graph](https://github.com/Twinside/Juicy.Pixels/blob/master/docimages/pixelgraph.svg), it looks like only `PixelF` (and effectively `PixelRGBF`) is leftover.

Could `Scaler16`'s scaler can be used to build an efficient+generic scaler? If not, could you consider exposing an `Experimental` module with your efforts (as demonstrated in comment from Oct17,2016)?

**Comment by mrkkrp** [comment]
I'll look what can be done next weekend.

**Comment by mrkkrp** [comment]
Sorry I did not manage to find time on this weekend to look into this, but this is in my todo list, so I'll get to this.

**Comment by mrkkrp** [comment]
Done, without performance regressions (almost). 0.3.0 will be on Hackage soon.

**Comment by naushadh** [comment]
You're the best!
