### ISSUE TITLE
resize with longest edge constraint, retaining ratio

### ISSUE THREAD

**Issue by afcondon** [mrkkrp/JuicyPixels-extra#8]
hi, i wrote something for my own needs using JuicyPixels-extra and wondered if you'd like a PR for the simple constrained resizer i needed to write in it?

if you're interested you can see code here: https://github.com/afcondon/juicy-pixel-processor/blob/master/app/Main.hs

**Comment by mrkkrp** [comment]
I'm not sure. From a quick look at the code, the part that is relevant to `JuicyPixels-extra` is choosing of new size, which can be done by the user and then the helpers from the library can be called.

**Comment by mrkkrp** [comment]
Making `scaleBilinear` polymorphic would be good, but it's not trivial.

**Comment by afcondon** [comment]
yeah, fair enough. just thought i'd offer!
